name: CI

on:
  push:
    branches: [ feature/ci ]
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  vagrant-up:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache diet-pi box
        id: cache-diet-pi-box
        uses: actions/cache@v2
        with:
          path: dietpi-bullseye.box
          key: ${{ runner.os }}-dietpi-${{ hashFiles('build.sh') }}
          restore-keys: |
            ${{ runner.os }}-dietpi-
      - name: Cache diet-pi loxberry box
        id: cache-diet-pi-loxberry-box
        uses: actions/cache@v2
        with:
          path: box/dietpi-bullseye.box
          key: ${{ runner.os }}-dietpi-loxberry-${{ hashFiles('build.sh') }}
          restore-keys: |
            ${{ runner.os }}-dietpi-loxberry-
     
      - name: Setup libvirt
        run: |
          sudo apt-get update
          sudo apt-get install -y libvirt-daemon-system libvirt-dev libvirt-clients virt-manager qemu-kvm ebtables libguestfs-tools  ruby-fog-libvirt
          sudo systemctl enable --now libvirtd
          sudo systemctl start libvirtd
          sudo usermod -aG libvirt $(whoami)
          groups
          sudo chmod 777 /var/run/libvirt/*
          ls -n /var/run/libvirt/
          virsh list  --all

      - name: Setup HashiCorp Vagrant
        run: |
          sudo apt-get remove vagrant
          sudo apt-get remove virtualbox
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update
          sudo apt install -y vagrant
          vagrant plugin install vagrant-libvirt
          

#      - name: Setup Virtualbox
#        run: |
#          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] https://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list
#          wget -O- https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo gpg --yes --output /usr/share/keyrings/oracle-virtualbox-2016.gpg --dearmor
#          sudo apt-get update
#          sudo apt-get install -y build-essential software-properties-common virtualbox
      - name: Check versions
        run: |
          vagrant --version
      - name: Generate vagrant box
        run: |
          sudo apt-get update
          sudo apt-get install guestmount
          chmod +x ./build.sh
          ./build.sh
        if: steps.cache-diet-pi-box.outputs.cache-hit != 'true'
      - name: import base box
        run: |
          ls -la
          vagrant box add --name dietpi-bullseye file://$PWD/dietpi-bullseye.box
          vagrant box list
        if: steps.cache-diet-pi-loxberry-box.outputs.cache-hit != 'true'
      - name: install loxberry
        run: |
          mkdir box
          cd box
          vagrant init dietpi-bullseye
          vagrant up --provider=libvirt 
          vagrant ssh -c "sudo wget https://raw.githubusercontent.com/mschlenstedt/Loxberry_Installer/main/install.sh && sudo  bash install.sh | sudo  tee /boot/loxberry_install.log"
          vagrant package --base dietpi-bullseye --output dietpi-bullseye-loxberry.box
        if: steps.cache-diet-pi-loxberry-box.outputs.cache-hit != 'true'
          